import type { PromptDefinition } from "../../types.js";
import { optionalArg, renderInputs, requireArg, userMessage } from "./helpers.js";

/**
 * MCP prompt version of the `dm-campaign-builder` Claude Code skill's
 * "Arc Builder" mode — see D:\github\dm-toolkit\dm-campaign-builder\SKILL.md.
 * No live Geektastic Realms data is read; this is a static instructional
 * template (transcribed verbatim from that skill) plus the user's argument
 * values interpolated in. See ROADMAP.md Phase 8 "Campaign Builder prompts".
 */

const INSTRUCTIONS = `Using the inputs above, produce a complete arc document in Markdown. Use the
structure below exactly, in the order given. Each section should be substantive and
specific — avoid generic placeholder language. Write for a DM who will run this at
the table, not a novelist writing for a reader.

The arc should have internal consistency: NPCs should appear in multiple beats, faction
goals should shape player choices, and the climax should feel like the culmination of
the beats that preceded it, not a scene dropped in from elsewhere.

## Design Principles

These six principles shape every arc generated by this mode. They are applied during
generation and audited in the Arc Design Compliance block at the end of every output.

- **Three-Act Structure** — beats map explicitly to Setup, Confrontation, or Resolution; all three acts must be present
- **BBEG Standard** — the primary villain is felt before the climax via at least two indirect or direct appearances in earlier beats
- **False Victory** — mandatory; one Confrontation beat where the players believe they have succeeded before circumstances reverse or deepen
- **Anti-Railroading Standard** — every beat must have a defined failure or divergence consequence; no beat should only work if players succeed
- **Three Pillars Balance** — the arc as a whole covers Combat, Exploration, and Roleplay across its beats
- **Escalating Stakes** — early beats establish the threat, middle beats complicate it, late beats force hard choices with real costs

---

#### Arc Overview
3–4 sentences. What is at stake, who the antagonist is, and what success or failure
looks like for the players. Be concrete — name the threat, name the cost.

#### Inciting Incident
The event that pulls the party in. Make it specific, dramatic, and immediately
actionable. Include one hook for each of the four common party motivations:
duty, greed, personal loss, and curiosity. These don't need to be separate scenes —
one event can offer all four angles.

#### Narrative Beats
5–7 key story beats in sequence. For each beat:

- **Beat Title** — a short evocative name, followed by its act label in brackets: \`[Setup]\`, \`[Confrontation]\`, or \`[Resolution]\`
- **What Happens** — one paragraph describing the event or revelation
- **Player Agency** — at least one meaningful choice the players face
- **Consequence Branch** — what changes if players succeed, fail, or choose differently

One Confrontation beat must be labeled \`[False Victory]\` — a moment where the players believe they have won before the situation reverses or deepens. This beat is mandatory.

Beats should escalate. Early beats establish stakes; middle beats complicate them;
late beats force hard choices. The party should feel the world reacting to what they do.

#### Key NPCs
3–5 NPCs central to the arc. For each:
- **Name**, role (ally / antagonist / wild card), one sentence of motivation
- One secret they carry — something players may or may not discover, that changes how
  they read this character if they find it

#### Faction Involvement
2–3 factions with a stake in the arc's outcome. For each:
- Their goal during this arc
- Whether they are potential allies, enemies, or both depending on player choices

Factions should create genuine tension — ideally at least one faction is neither
straightforwardly good nor evil, giving players a real decision about alignment.

#### Escalation & Pacing
Describe how the threat grows across the arc. Include:
- One moment of apparent victory that turns into a setback — this is your \`[False Victory]\` beat; confirm it is labeled as such in Narrative Beats
- One moment of revelation where players realize the stakes are higher than assumed

These are not optional — they are what separate a memorable arc from a sequence of encounters.

For any beat with a single success path, apply an Anti-Railroading check: name what happens if players fail, refuse, or take an unexpected approach. A beat that only works if players succeed is a design flaw, not a dramatic necessity.

#### Climax
The climactic encounter or scene:
- Location (make it evocative and narratively resonant — not just a dungeon room)
- Who is present and what they want
- What the players must do to succeed
- What success looks like narratively, not just mechanically

#### Arc Resolution
Two possible endings:
1. **Success** — what has changed in the world, what the players have earned or lost,
   and what this victory costs
2. **Failure** — what the antagonist achieves, how the world is worse, and whether
   there is still something worth fighting for

Both endings should feel real. A failure state that ends the campaign is a poor failure
state — give players a world they can still act in.

#### Seeds for the Next Arc
2–3 unanswered questions or new threats introduced by this arc's resolution.
These should feel like natural consequences, not bolted-on sequel hooks.

---

### Output Format

Format the full arc as Markdown using headers and subheaders suitable for use in
Obsidian. Bold NPC names and faction names on first mention. No emojis. Write in
present tense for beat descriptions ("The party arrives to find...") and past/future
framing for resolution sections.

After the Seeds for the Next Arc section, append an \`#### Arc Design Compliance\` block listing which of the six Design Principles are satisfied and flagging any gaps:

#### Arc Design Compliance

| Principle | Status | Notes |
|---|---|---|
| Three-Act Structure | Satisfied / Gap | [Which acts are covered] |
| BBEG Standard | Satisfied / Gap | [Villain appearances noted] |
| False Victory | Satisfied / Gap | [Beat name and act position] |
| Anti-Railroading Standard | Satisfied / Gap | [Any forced success sequences flagged] |
| Three Pillars Balance | Satisfied / Gap | [Which pillars are covered] |
| Escalating Stakes | Satisfied / Gap | [Pacing assessment] |`;

const WORLD_INTEGRATION = `---

### Campaign World Integration

Using the campaign world details supplied above, weave the relevant setting elements into the output. Consider:
- How local power structures or factions shape the content
- Any cultural, religious, or political details specific to the setting
- World-specific constraints, lore, or flavor the user mentioned
- Unique setting elements that would distinguish this content from generic fantasy

Add this as its own \`#### Campaign World Integration\` section after Seeds for the Next Arc (before Arc Design Compliance).`;

export const arcBuilderPrompt: PromptDefinition = {
  name: "campaign_arc_builder",
  description:
    "Design a complete, playable multi-session D&D story arc — beats, tension, escalation, and payoffs — " +
    "structured for actual use at the table. Converted from the dm-campaign-builder skill's Arc Builder mode.",
  arguments: [
    { name: "campaign_setting", description: "A named world or a freeform setting description.", required: true },
    {
      name: "world_details",
      description:
        "Setting-specific factions, powers, locations, lore, or flavor to weave in (e.g. a dominant religion, a ruling faction, cultural details).",
    },
    { name: "party_level_range", description: 'e.g. "5-10".', required: true },
    { name: "session_count", description: 'Estimated session count, e.g. "8-12".', required: true },
    { name: "central_conflict", description: "If omitted, one is generated to fit the setting and tone." },
    {
      name: "tone",
      description: "Dark / Heroic / Political / Horror / Mystery / Epic — combinations allowed.",
      required: true,
    },
    { name: "pc_hooks", description: "Backstory elements to weave into the arc." },
  ],
  async handler(args) {
    const campaignSetting = requireArg(args, "campaign_setting");
    const partyLevelRange = requireArg(args, "party_level_range");
    const sessionCount = requireArg(args, "session_count");
    const tone = requireArg(args, "tone");
    const worldDetails = optionalArg(args, "world_details");
    const centralConflict = optionalArg(args, "central_conflict");
    const pcHooks = optionalArg(args, "pc_hooks");

    const inputs = renderInputs([
      { label: "Campaign Setting", value: campaignSetting },
      { label: "Campaign World Details", value: worldDetails },
      { label: "Party Level Range", value: partyLevelRange },
      { label: "Estimated Session Count", value: sessionCount },
      { label: "Central Conflict", value: centralConflict ?? "(not given — generate one that fits the setting and tone)" },
      { label: "Tone", value: tone },
      { label: "PC Hooks", value: pcHooks },
    ]);

    const parts = [inputs, "", INSTRUCTIONS];
    if (worldDetails) parts.push("", WORLD_INTEGRATION);

    return { description: "Arc Builder — multi-session story arc design", messages: userMessage(parts.join("\n")) };
  },
};
